server:
  port: 8083

spring:
    datasource:
#        url: jdbc:mysql://localhost:3306/activiti?useUnicode=true&characterEncoding=utf8&useSSL=false
#        username: root
#        password: root123
 #       driver-class-name: com.mysql.jdbc.Driver
         name: druidDataSource
         type: com.alibaba.druid.pool.DruidDataSource
         druid:
           driver-class-name: com.mysql.jdbc.Driver
           url: jdbc:mysql://localhost:3306/activiti?useUnicode=true&characterEncoding=utf8&useSSL=false
           username: root
           password: root123
           filters: stat,wall,log4j,config
           max-active: 100
           initial-size: 1
           max-wait: 60000
           min-idle: 1
           time-between-eviction-runs-millis: 60000
           min-evictable-idle-time-millis: 300000
           validation-query: select 'x'
           test-while-idle: true
           test-on-borrow: false
           test-on-return: false
           pool-prepared-statements: true
           max-open-prepared-statements: 50
           max-pool-prepared-statement-per-connection-size: 20
# redis 配置
    redis:
      database: 0
      host: localhost
      port: 6379
      password:
      jedis:
        pool:
          max-active: 8
          min-idle: 0
          max-idle: 8
          max-wait: -1
      timeout: 5000

    messages:
      encoding: utf-8
      basename: i18n/shop/message

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  config-location: classpath:mybatis-page-config.xml

mapper:
  mappers: com.youhe.mapper



