server:
  port: 80

spring:
  datasource:
    #        url: jdbc:mysql://localhost:3306/activiti?useUnicode=true&characterEncoding=utf8&useSSL=false
    #        username: root
    #        password: root123
    #       driver-class-name: com.mysql.jdbc.Driver
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/activiti?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: root
      filters: stat,wall,log4j,config
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
      web-stat-filter:
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤格式
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        # 设置ip白名单
        allow: 127.0.0.1
        # 设置ip黑名单，优先级高于白名单
        deny:
        # 设置控制台管理用户
        login-username: root
        login-password: root
        # 是否可以重置数据
        reset-enable: false

  # redis 配置
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    pool:
      maxIdel: 0
      maxWaitMillis: 1000
      maxTotal: 30
      minEvictableIdleTimeMillis: 1800000
      minIdel: 0
      lifo: false
      softMinEvictableIdleTimeMillis: 1800000
    timeout: 0

  messages:
    encoding: utf-8
    basename: i18n/shop/message

  # activiti 配置
  activiti:
    check-process-definitions: false
    database-schema-update: true
    database-schema: ACT

#  mvc:
#    static-path-pattern: /static/**
# mybatis配置
#mybatis:
#  mapper-locations: classpath:mapper/**/*.xml
#  config-location: classpath:mybatis-page-config.xml

# mybatis-plus 配置
mybatis-plus:
  check-config-location: false
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.youhe.entity
#  configuration:
#    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      table-underline: true
