
-- 文档中心
-- 知识管理
DROP TABLE IF EXISTS `file_knowledge`;
CREATE TABLE `file_knowledge`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `UPLOAD_DATE` datetime(3) NULL DEFAULT NULL,
  `FILE_NAME` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '文件名称',
  `UPLOAD_PEOPLE` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '上传人',
  `FILE_CATEGORY_NUMBER` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '文件所属类别编号',
  `FILE_CATEGORY_NAME` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '文件所属类别名称',
  `FILE_TYPE` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '文件类型',
  `SAVE_FILE_NAME` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '保存到服务器目录的文件名称',
  `SERVER_ADDR` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '保存到服务器目录的文件全路径',
  `FILE_SIZE` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '文件大小',
  `VERSION_NUMBER` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL  COMMENT '备用',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;


-- 规章制度
DROP TABLE IF EXISTS `file_rule`;
CREATE TABLE `file_rule`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `UPLOAD_DATE` datetime(3) NULL DEFAULT NULL,
  `FILE_NAME` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '文件名称',
  `UPLOAD_PEOPLE` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '上传人',
  `FILE_CATEGORY_NUMBER` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '文件所属类别编号',
  `FILE_CATEGORY_NAME` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '文件所属类别名称',
  `FILE_TYPE` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '文件类型',
  `SAVE_FILE_NAME` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '保存到服务器目录的文件名称',
  `SERVER_ADDR` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '保存到服务器目录的文件全路径',
  `FILE_SIZE` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '文件大小',
  `VERSION_NUMBER` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL  COMMENT '备用',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;